version: "3.9"

services:
  app:
    image: trupro-backend:1.0
    build:
      context: .
      dockerfile: admin-api/Dockerfile
    container_name: trupro-backend
    env_file:
      - .env
      - firebase.env
    ports:
      - "8080:8080"
      - "5005:5005"
    depends_on:
      - db
    links:
      - db
    command: [ "java", "-Xmx2048m", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005", "-jar", "/app.jar", "--server.port=8080" ]

  db:
    image: postgres:13.1
    container_name: db-backend
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
