ALTER TABLE file ADD COLUMN name VARCHAR(255);
ALTER TABLE file ADD COLUMN size INTEGER;

UPDATE file SET name = '' WHERE name IS NULL;
UPDATE file SET size=0 WHERE size is NULL;

ALTER TABLE file ALTER COLUMN name SET NOT NULL;
ALTER TABLE file ALTER COLUMN size SET NOT NULL;
