spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    hikari:
      maximum-pool-size: 20
    flyway:
      enabled: true
      locations: classpath:db/migration
    jackson:
      default-property-inclusion: non_null
      mapper.accept_case_insensitive_enums: true
      serialization.indent_output: true
    jpa:
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      open-in-view: false
      show-sql: true
      format_sql: true
    output:
      ansi:
        enabled: always
management:
  endpoint.health.probes.enabled: true
  endpoint.loggers.enabled: true
  endpoint.prometheus.enabled: true
  endpoint.info.enabled: true
  endpoints.web.exposure.include: "info, health, loggers, prometheus"
  #otherwise stream will not pass health checks
  endpoints:
    web:
      base-path: /stream/actuator
#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
#    root: DEBUG
#    org.springframework.web: DEBUG
#    level.org.hibernate: DEBUG
#    org.springframework.boot.actuate.health: DEBUG
#    org.springframework.data.r2dbc: DEBUG
#  pattern.console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}) %clr(%5p) %clr(:){faint} %replace(%m){\"password=.*, \", \"password=xxx, \"}%n%wEx"
server:
  address: 0.0.0.0
  port: 8086
  error:
    include-message: always
task:
  poolSize: 5
  threadNamePrefix: "ThreadPoolTaskScheduler"
